import { StyleSheet } from 'react-native';
export default styles = StyleSheet.create({
  optionCard: {
    alignParentLeft: true,
    alignParentTop: true,
    width: 150,
    height: 231,
    marginLeft: 8,
    marginTop: 150,
    backgroundColor: '#46425B',
    elevation: 4,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  optionCard1: {
    alignParentLeft: true,
    alignParentTop: true,
    position: 'absolute',
    width: 150,
    height: 231,
    marginLeft: 185,
    marginTop: 150,
    backgroundColor: '#46425B',
    elevation: 4,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    // box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25),
    // border-radius: 20px 20px 10px 10px
  },
  optionCard2: {
    alignParentLeft: true,
    alignParentTop: true,
    position: 'absolute',
    width: 150,
    height: 231,
    marginLeft: 8,
    marginTop: 412,
    elevation: 4,
    backgroundColor: '#46425B',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    // box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25),
    // border-radius: 20px 20px 10px 10px
  },
  optionCard3: {
    alignParentLeft: true,
    alignParentTop: true,
    width: 150,
    height: 231,
    marginLeft: 185,
    marginTop: 32,
    elevation: 4,
    backgroundColor: '#46425B',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    // border-radius: 20px 20px 10px 10px
  },
  OptImg: {
    width: 150,
    height: 100,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  OptTxt: {
    color: '#ffffff',
    height: 26,
    fontFamily: 'Bebas Neue',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '700',
    top: 10,
    textAlign: 'center',
  },
  buttonWhiteText: {
    fontSize: 12,
    textAlign: 'center',
    top: 6,
    color: '#000',
    fontWeight: 'bold',
  },
  primaryButton: {
    backgroundColor: '#FEDB29',
    borderRadius: 30,
    color: '#ff5c5c',
    height: 30,
    width: 100,
    left: 25,
    top: 30,
  },
  scroll: {
    backgroundColor: '#F5F5F5',
    padding: 30,
    height: '100%',
    width: '100%',
    flexDirection: 'row',
  },
});
